services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Mapeia a porta 4000 para o host
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Ignora node_modules no hot reload
    environment:
      - NODE_ENV=development # Garante o ambiente de desenvolvimento
    stdin_open: true
    tty: true

  db:
    image: postgres:17 # Ajuste para a versão 17 do PostgreSQL
    environment:
      POSTGRES_DB: isommelier
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sommelier
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Porta padrão para acessar o banco de dados

volumes:
  postgres_data: